name: Renovate
on:
  schedule:
    - cron: '0 3 * * 1' # weekly, every Monday at 3am UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    name: Run Renovate Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.0
        with:
          configurationFile: renovate-config.js
          token: '${{ secrets.RENOVATE_TOKEN }}'
